---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source
  template:
    metadata:
      labels:
        app: source
    spec:
      volumes:
        - name: tls
          secret:
            secretName: source-tls
        # configmap化
        - name: nginx-conf
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/source/nginx.conf
            type: File
        # configmap化
        - name: default-conf
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/source/default.conf
            type: File
        - name: profile
          hostPath:
            path: ${HOME}/home/sbin/profile.sh
            type: File
        - name: install
          hostPath:
            path: ${HOME}/home/sbin/install.sh
            type: File
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls
              mountPath: /etc/nginx/tls/
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
            - name: profile
              mountPath: /usr/share/nginx/html/sbin/profile.sh
              readOnly: true
            - name: install
              mountPath: /usr/share/nginx/html/sbin/install.sh
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: source
spec:
  selector:
    app: source
  ports:
    - port: 443
