---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
    spec:
      volumes:
        - name: tls
          secret:
            secretName: webdav-tls
        # configmap化
        - name: nginx-conf
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/webdav/nginx.conf
            type: File
        # configmap化
        - name: default-conf
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/webdav/default.conf
            type: File
        - name: h5ai
          hostPath:
            path: ${HOME}/home/local/src/de.larsjung.h5ai/
            type: DirectoryOrCreate
        - name: share
          flexVolume:
            driver: tkyz/mnt
            fsType: mnt
            readOnly: true
            options:
              name: share
              path: /
              fmod: "0644"
              dmod: "0755"
        - name: pub
          flexVolume:
            driver: tkyz/mnt
            fsType: mnt
            readOnly: true
            options:
              name: pub
              path: /
              fmod: "0644"
              dmod: "0755"
      initContainers:
        - name: init
          image: alpine/git:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: h5ai
              mountPath: /workdir/main/
          command: ['sh', '-c']
          args:
            - |
              git clone --branch v0.29.2 https://github.com/lrsjng/h5ai.git /workdir/main/ || true
              # TODO: npm install
              # TODO: npm run build
              find /workdir/ -type f -print0 | xargs -0 chmod 666
              find /workdir/ -type d -print0 | xargs -0 chmod 777
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls
              mountPath: /etc/nginx/tls/
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
            - name: h5ai
              mountPath: /usr/share/nginx/html/
              readOnly: true
            - name: share
              mountPath: /usr/share/nginx/html/build/share/
              readOnly: true
            - name: pub
              mountPath: /usr/share/nginx/html/build/pub/
              readOnly: true
        - name: php-fpm
          image: docker.repos.tkyz.jp/php-fpm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: h5ai
              mountPath: /usr/share/nginx/html/
            - name: share
              mountPath: /usr/share/nginx/html/build/share/
              readOnly: true
            - name: pub
              mountPath: /usr/share/nginx/html/build/pub/
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: webdav
spec:
  selector:
    app: webdav
  ports:
    - port: 443
