---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      volumes:
        - name: tls
          secret:
            secretName: wiki-tls
        # configmap化
        - name: nginx-conf
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/wiki/nginx/nginx.conf
            type: File
        # configmap化
        - name: default-conf
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/wiki/nginx/default.conf
            type: File
        - name: dokuwiki
          hostPath:
            path: ${HOME}/home/local/src/org.dokuwiki/
            type: DirectoryOrCreate
        # configmap化
        - name: dokuwiki-acl
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/wiki/dokuwiki/acl.auth.php
            type: File
        # configmap化
        - name: dokuwiki-local
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/wiki/dokuwiki/local.php
            type: File
        # configmap化
        - name: dokuwiki-plugins
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/wiki/dokuwiki/plugins.local.php
            type: File
        # configmap化
        - name: dokuwiki-users
          hostPath:
            path: ${HOME}/home/src/k8s/configmap/home/wiki/dokuwiki/users.auth.php
            type: File
        - name: dokuwiki-pages
#         hostPath:
#           path: ${HOME}/home/var/wiki/pages/
#           type: DirectoryOrCreate
          flexVolume:
            driver: tkyz/mnt
            fsType: mnt
            options:
              name: wiki
              path: /pages/
              fmod: "0666"
              dmod: "0777"
        - name: dokuwiki-media
#         hostPath:
#           path: ${HOME}/home/var/wiki/media/
#           type: DirectoryOrCreate
          flexVolume:
            driver: tkyz/mnt
            fsType: mnt
            options:
              name: wiki
              path: /media/
              fmod: "0666"
              dmod: "0777"
      initContainers:
        - name: init
          image: alpine/git:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: dokuwiki
              mountPath: /workdir/main/
            - name: dokuwiki-acl
              mountPath: /workdir/conf/acl.auth.php
            - name: dokuwiki-local
              mountPath: /workdir/conf/local.php
            - name: dokuwiki-plugins
              mountPath: /workdir/conf/plugins.local.php
            - name: dokuwiki-users
              mountPath: /workdir/conf/users.auth.php
            - name: dokuwiki-pages
              mountPath: /workdir/data/pages/
            - name: dokuwiki-media
              mountPath: /workdir/data/media/
          command: ['sh', '-c']
          args:
            - |
              git clone --branch release_stable_2018-04-22c https://github.com/splitbrain/dokuwiki.git                     /workdir/main/                         || true
              git clone --branch 2020-03-24                 https://github.com/splitbrain/dokuwiki-plugin-translation.git  /workdir/main/lib/plugins/translation/ || true
              git clone --branch v2020-04-04                https://github.com/giterlizzi/dokuwiki-template-bootstrap3.git /workdir/main/lib/tpl/bootstrap3/      || true
              git clone --branch master                     https://github.com/samuelet/indexmenu.git                      /workdir/main/lib/plugins/indexmenu/   || true
              find /workdir/ -type f -print0 | xargs -0 chmod 666
              find /workdir/ -type d -print0 | xargs -0 chmod 777
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls
              mountPath: /etc/nginx/tls/
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
            - name: dokuwiki
              mountPath: /usr/share/nginx/html/
              readOnly: true
        - name: php-fpm
          image: docker.repos.tkyz.jp/php-fpm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: dokuwiki
              mountPath: /usr/share/nginx/html/
            - name: dokuwiki-acl
              mountPath: /usr/share/nginx/html/conf/acl.auth.php
            - name: dokuwiki-local
              mountPath: /usr/share/nginx/html/conf/local.php
            - name: dokuwiki-plugins
              mountPath: /usr/share/nginx/html/conf/plugins.local.php
            - name: dokuwiki-users
              mountPath: /usr/share/nginx/html/conf/users.auth.php
            - name: dokuwiki-pages
              mountPath: /usr/share/nginx/html/data/pages/
            - name: dokuwiki-media
              mountPath: /usr/share/nginx/html/data/media/

---
apiVersion: v1
kind: Service
metadata:
  name: wiki
spec:
  selector:
    app: wiki
  ports:
    - port: 443
