---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql
          image: postgres:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "sandbox"
            - name: POSTGRES_PASSWORD
              value: "sandbox"
            - name: POSTGRES_DB
              value: "sandbox"

---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: sandbox
spec:
  type: LoadBalancer
  selector:
    app: pgsql
  ports:
    - port: 5432
      nodePort: 5432
